//
//  extension.shared.keys.swift
//  MrArthur
//
//  Created by Reille Sebastien on 01/10/2022.
//

import Foundation

class ExtensionSharedAppGroupService {
    static let sharedDefault = UserDefaults(suiteName: ExtensionSharedAppGroupService.keys.APP_GROUP_KEY)
    
    struct keys {
        // Dev
        // TODO: remove
        static let TEST_KEY: String = "TEST_KEY"
        static let TEST_VIEW_OBS: String = "TEST_VIEW_OBS"
        static let TRIGGER_COUNT = "TRIGGER_COUNT"
        static let EVENT_TIME_ADD = "EVENT_TIME_ADD"

        // App Group
        static let APP_GROUP_KEY: String = "group.extension-target"

        // Screen Time (ST for ScreenTime, QT for quarter)
            // Selection
        static let ENTERTAINMENT_FAMILY_ACTIVITY_SELECTION = "ENTERTAINMENT_FAMILY_ACTIVITY_SELECTION"
        static let EDUCATIONAL_FAMILY_ACTIVITY_SELECTION = "EDUCATIONAL_FAMILY_ACTIVITY_SELECTION"
        static let ALL_CATEGORY_FAMILY_ACTIVITY_SELECTION = "ALL_CATEGORY_FAMILY_ACTIVITY_SELECTION"
        static let FORBIDDEN_BROWSERS_FAMILY_ACTIVITY_SELECTION = "FORBIDDEN_BROWSERS_FAMILY_ACTIVITY_SELECTION"
            // Shield
        static let SHIELD_MESSAGE_TITLE = "SHIELD_MESSAGE_TITLE"
        static let SHIELD_MESSAGE_SUB_TITLE = "SHIELD_MESSAGE_SUB_TITLE"
        static let SHIELD_MESSAGE_PRIMARY_BUTTON_LABEL = "SHIELD_MESSAGE_SUB_TITLE"
            // Total
        static let TOTAL_ST_SECOND_PER_DAY_ALLOWED = "TOTAL_ST_SECOND_PER_DAY_ALLOWED"
        static let TOTAL_ST_SECOND_PER_DAY_ALLOWED_REACHED = "TOTAL_ST_SECOND_PER_DAY_ALLOWED_REACHED"
            // Entertainment
        static let ENTERTAINMENT_ST_SECOND_PER_DAY_ALLOWED = "ENTERTAINMENT_ST_SECOND_PER_DAY_ALLOWED"
        static let ENTERTAINMENT_ST_SECOND_SPENT_DAY_LOCAL_DEVICE = "ENTERTAINMENT_ST_SECOND_SPENT_DAY_LOCAL_DEVICE"
        static let ENTERTAINMENT_ST_SECOND_SPENT_DAY_LOCAL_DEVICE_DOUBLE = "ENTERTAINMENT_ST_SECOND_SPENT_DAY_LOCAL_DEVICE_DOUBLE"
        static let ENTERTAINMENT_ST_SECOND_SPENT_DAY_MULTI_DEVICE = "ENTERTAINMENT_ST_SECOND_SPENT_DAY_MULTI_DEVICE"
        static let ENTERTAINMENT_ST_SECOND_QUARTER_1 = "ENTERTAINMENT_ST_SECOND_QUARTER_1"
        static let ENTERTAINMENT_ST_SECOND_QUARTER_2 = "ENTERTAINMENT_ST_SECOND_QUARTER_2"
        static let ENTERTAINMENT_ST_SECOND_QUARTER_3 = "ENTERTAINMENT_ST_SECOND_QUARTER_3"
        static let ENTERTAINMENT_ST_SECOND_QUARTER_4 = "ENTERTAINMENT_ST_SECOND_QUARTER_4"
        static let ENTERTAINMENT_ST_SECOND_MORNING_ADVANCE = "ENTERTAINMENT_ST_SECOND_MORNING_ADVANCE"
        static let ENTERTAINMENT_ST_SECOND_ADVANTAGE_OVER_YESTERDAY_CONSUMPTION =
                "ENTERTAINMENT_ST_SECOND_ADVANTAGE_OVER_YESTERDAY_CONSUMPTION"
        static let ENTERTAINMENT_CATEGORIES_BLOCKED = "ENTERTAINMENT_CATEGORIES_BLOCKED"
        static let ENTERTAINMENT_ST_SECOND_TIME_LEFT = "ENTERTAINMENT_ST_SECOND_TIME_LEFT"
            // Educational
        static let EDUCATIONAL_ST_SECOND_PER_DAY_COMMITMENT = "EDUCATIONAL_ST_SECOND_PER_DAY_COMMITMENT"
        static let EDUCATIONAL_ST_SECOND_SPENT_DAY_LOCAL_DEVICE = "EDUCATIONAL_ST_SECOND_SPENT_DAY_LOCAL_DEVICE"
        static let EDUCATIONAL_ST_SECOND_SPENT_DAY_LOCAL_DEVICE_DOUBLE = "EDUCATIONAL_ST_SECOND_SPENT_DAY_LOCAL_DEVICE_DOUBLE"
        static let EDUCATIONAL_ST_SECOND_SPENT_DAY_MULTI_DEVICE = "EDUCATIONAL_ST_SECOND_SPENT_DAY_MULTI_DEVICE"
        static let EDUCATIONAL_ST_SECOND_QUARTER_1 = "EDUCATIONAL_ST_SECOND_QUARTER_1"
        static let EDUCATIONAL_ST_SECOND_QUARTER_2 = "EDUCATIONAL_ST_SECOND_QUARTER_2"
        static let EDUCATIONAL_ST_SECOND_QUARTER_3 = "EDUCATIONAL_ST_SECOND_QUARTER_3"
        static let EDUCATIONAL_ST_SECOND_QUARTER_4 = "EDUCATIONAL_ST_SECOND_QUARTER_4"
        static let EDUCATIONAL_ST_QUARTER_ON_GOING = "EDUCATIONAL_ST_SECOND_QUARTER_ON_GOING"
            // All categories
        static let ALL_CATEGORIES_ST_SECOND_SPENT_DAY_LOCAL_DEVICE_DOUBLE = "ALL_CATEGORIES_ST_SECOND_SPENT_DAY_LOCAL_DEVICE_DOUBLE"
        static let ALL_CATEGORIES_ST_SECOND_SPENT_DAY_LOCAL_DEVICE = "ALL_CATEGORIES_ST_SECOND_SPENT_DAY_LOCAL_DEVICE"
        static let ALL_CATEGORIES_ST_SECOND_SPENT_DAY_MULTI_DEVICE = "ALL_CATEGORIES_ST_SECOND_SPENT_DAY_MULTI_DEVICE"
            // Rest Period
        static let IS_REST_PERIOD_ST_BOOLEAN = "IS_REST_PERIOD_ST_BOOLEAN"
        static let HAS_REST_PERIOD_ST_BOOLEAN = "HAS_REST_PERIOD_ST_BOOLEAN"
        static let MORNING_START_DAY_MONTH = "MORNING_START_DAY_MONTH"
        static let REST_PERIOD_ST_START_TIME_HOUR = "REST_PERIOD_ST_START_TIME_HOUR"
        static let REST_PERIOD_ST_END_TIME_HOUR = "REST_PERIOD_ST_END_TIME_HOUR"
        static let REST_PERIOD_HAS_ALREADY_STARTED_TODAY_ST_BOOLEAN = "REST_PERIOD_HAS_ALREADY_STARTED_TODAY_ST_BOOLEAN"
            // Neutral Media
        static let NEUTRAL_MEDIA_ACTIVATED_BOOLEAN = "NEUTRAL_MEDIA_ACTIVATED_BOOLEAN"
            // Date
        static let TODAY_DATE_TIME_ZONED = "TODAY_DATE_TIME_ZONED"
        static let TODAY_DATE_TIME_ZONED_DESCRIPTION = "TODAY_DATE_TIME_ZONED_DESCRIPTION"
            // Token
        static let USER_TOKEN_HAS_CHANGED = "USER_TOKEN_HAS_CHANGED"
//        static let TODAY_INCREMENTAL_NUMBER = "TODAY_INCREMENTAL_NUMBER"
            // API
        static let API_BASE_URL = "API_BASE_URL"
    }

    struct shieldMessage {
        struct hasToDoEducationalTime {
            static let TITLE: String = "It's enough!"
            static let SUB_TITLE: String = "Do some educational screen time to get more entertainment time."
            static let BUTTON_LABEL: String = "OK"
        }
    }
}
