//
//  extension.device.activity.schedule.name.list.swift
//  MrArthur
//
//  Created by Reille Sebastien on 09/12/2022.
//

import SwiftUI
import Foundation
import FamilyControls
import DeviceActivity
import ManagedSettings

let slotDeviceActivityNameList: Array<DeviceActivityName> = [
    DeviceActivityName.slot1ActivityName,
    DeviceActivityName.slot2ActivityName,
    DeviceActivityName.slot3ActivityName,
    DeviceActivityName.slot4ActivityName,
    DeviceActivityName.slot5ActivityName,
    DeviceActivityName.slot6ActivityName,
    DeviceActivityName.slot7ActivityName,
    DeviceActivityName.slot8ActivityName,
    DeviceActivityName.slot9ActivityName,
    DeviceActivityName.slot10ActivityName,
    DeviceActivityName.slot11ActivityName,
    DeviceActivityName.slot12ActivityName,
//    DeviceActivityName.slot13ActivityName,
//    DeviceActivityName.slot14ActivityName,
//    DeviceActivityName.slot15ActivityName,
//    DeviceActivityName.slot16ActivityName,
//    DeviceActivityName.slot17ActivityName,
//    DeviceActivityName.slot18ActivityName,
//    DeviceActivityName.slot19ActivityName,
//    DeviceActivityName.slot20ActivityName,
//    DeviceActivityName.slot21ActivityName,
//    DeviceActivityName.slot22ActivityName,
//    DeviceActivityName.slot23ActivityName,
//    DeviceActivityName.slot24ActivityName,
//    DeviceActivityName.slot25ActivityName,
//    DeviceActivityName.slot26ActivityName,
//    DeviceActivityName.slot27ActivityName,
//    DeviceActivityName.slot28ActivityName,
//    DeviceActivityName.slot29ActivityName,
//    DeviceActivityName.slot30ActivityName,
//    DeviceActivityName.slot31ActivityName,
//    DeviceActivityName.slot32ActivityName,
//    DeviceActivityName.slot33ActivityName,
//    DeviceActivityName.slot34ActivityName,
//    DeviceActivityName.slot35ActivityName,
//    DeviceActivityName.slot36ActivityName,
//    DeviceActivityName.slot37ActivityName,
//    DeviceActivityName.slot38ActivityName,
//    DeviceActivityName.slot39ActivityName,
//    DeviceActivityName.slot40ActivityName,
//    DeviceActivityName.slot41ActivityName,
//    DeviceActivityName.slot42ActivityName,
//    DeviceActivityName.slot43ActivityName,
//    DeviceActivityName.slot44ActivityName,
//    DeviceActivityName.slot45ActivityName,
//    DeviceActivityName.slot46ActivityName,
//    DeviceActivityName.slot47ActivityName,
//    DeviceActivityName.slot48ActivityName,
//    DeviceActivityName.slot49ActivityName,
//    DeviceActivityName.slot50ActivityName,
//    DeviceActivityName.slot51ActivityName,
//    DeviceActivityName.slot52ActivityName,
//    DeviceActivityName.slot53ActivityName,
//    DeviceActivityName.slot54ActivityName,
//    DeviceActivityName.slot55ActivityName,
//    DeviceActivityName.slot56ActivityName,
//    DeviceActivityName.slot57ActivityName,
//    DeviceActivityName.slot58ActivityName,
//    DeviceActivityName.slot59ActivityName,
//    DeviceActivityName.slot60ActivityName,
//    DeviceActivityName.slot61ActivityName,
//    DeviceActivityName.slot62ActivityName,
//    DeviceActivityName.slot63ActivityName,
//    DeviceActivityName.slot64ActivityName,
//    DeviceActivityName.slot65ActivityName,
//    DeviceActivityName.slot66ActivityName,
//    DeviceActivityName.slot67ActivityName,
//    DeviceActivityName.slot68ActivityName,
//    DeviceActivityName.slot69ActivityName,
//    DeviceActivityName.slot70ActivityName,
//    DeviceActivityName.slot71ActivityName,
//    DeviceActivityName.slot72ActivityName,
]
