//
//  extension.device.activity.schedule.name.service.swift
//  MrArthur
//
//  Created by Reille Sebastien on 09/12/2022.
//

import SwiftUI
import Foundation
import FamilyControls
import DeviceActivity
import ManagedSettings

extension DeviceActivityName {
    // Entertainment
    static let entertainmentActivityName = Self("entertainmentActivityName")
    static let entertainmentCorrection1ActivityName = Self("entertainmentCorrection1ActivityName")
    static let entertainmentCorrection2ActivityName = Self("entertainmentCorrection2ActivityName")
    static let entertainmentCorrection3ActivityName = Self("entertainmentCorrection3ActivityName")
    static let entertainmentCorrection4ActivityName = Self("entertainmentCorrection4ActivityName")
    static let entertainmentCorrection5ActivityName = Self("entertainmentCorrection5ActivityName")
    static let entertainmentCorrection6ActivityName = Self("entertainmentCorrection6ActivityName")
    static let entertainmentCorrection7ActivityName = Self("entertainmentCorrection7ActivityName")
    static let entertainmentCorrection8ActivityName = Self("entertainmentCorrection8ActivityName")
    static let entertainmentCorrection9ActivityName = Self("entertainmentCorrection9ActivityName")
    static let entertainmentCorrection10ActivityName = Self("entertainmentCorrection10ActivityName")
    
    static let educationalActivityName = Self("educationalActivityName")
    static let allCategoriesActivityName = Self("allCategoriesActivityName")
    static let restPeriodActivityName = Self("restPeriodActivityName")
    static let activityPeriodActivityName = Self("activityPeriodActivityName")
    
    // slots
    static let slot1ActivityName = Self("slot1ActivityName")
    static let slot2ActivityName = Self("slot2ActivityName")
    static let slot3ActivityName = Self("slot3ActivityName")
    static let slot4ActivityName = Self("slot4ActivityName")
    static let slot5ActivityName = Self("slot5ActivityName")
    static let slot6ActivityName = Self("slot6ActivityName")
    static let slot7ActivityName = Self("slot7ActivityName")
    static let slot8ActivityName = Self("slot8ActivityName")
    static let slot9ActivityName = Self("slot9ActivityName")
    static let slot10ActivityName = Self("slot10ActivityName")
    static let slot11ActivityName = Self("slot11ActivityName")
    static let slot12ActivityName = Self("slot12ActivityName")
//    static let slot13ActivityName = Self("slot13ActivityName")
//    static let slot14ActivityName = Self("slot14ActivityName")
//    static let slot15ActivityName = Self("slot15ActivityName")
//    static let slot16ActivityName = Self("slot16ActivityName")
//    static let slot17ActivityName = Self("slot17ActivityName")
//    static let slot18ActivityName = Self("slot18ActivityName")
//    static let slot19ActivityName = Self("slot19ActivityName")
//    static let slot20ActivityName = Self("slot20ActivityName")
//    static let slot21ActivityName = Self("slot21ActivityName")
//    static let slot22ActivityName = Self("slot22ActivityName")
//    static let slot23ActivityName = Self("slot23ActivityName")
//    static let slot24ActivityName = Self("slot24ActivityName")
//    static let slot25ActivityName = Self("slot25ActivityName")
//    static let slot26ActivityName = Self("slot26ActivityName")
//    static let slot27ActivityName = Self("slot27ActivityName")
//    static let slot28ActivityName = Self("slot28ActivityName")
//    static let slot29ActivityName = Self("slot29ActivityName")
//    static let slot30ActivityName = Self("slot30ActivityName")
//    static let slot31ActivityName = Self("slot31ActivityName")
//    static let slot32ActivityName = Self("slot32ActivityName")
//    static let slot33ActivityName = Self("slot33ActivityName")
//    static let slot34ActivityName = Self("slot34ActivityName")
//    static let slot35ActivityName = Self("slot35ActivityName")
//    static let slot36ActivityName = Self("slot36ActivityName")
//    static let slot37ActivityName = Self("slot37ActivityName")
//    static let slot38ActivityName = Self("slot38ActivityName")
//    static let slot39ActivityName = Self("slot39ActivityName")
//    static let slot40ActivityName = Self("slot40ActivityName")
//    static let slot41ActivityName = Self("slot41ActivityName")
//    static let slot42ActivityName = Self("slot42ActivityName")
//    static let slot43ActivityName = Self("slot43ActivityName")
//    static let slot44ActivityName = Self("slot44ActivityName")
//    static let slot45ActivityName = Self("slot45ActivityName")
//    static let slot46ActivityName = Self("slot46ActivityName")
//    static let slot47ActivityName = Self("slot47ActivityName")
//    static let slot48ActivityName = Self("slot48ActivityName")
//    static let slot49ActivityName = Self("slot49ActivityName")
//    static let slot50ActivityName = Self("slot50ActivityName")
//    static let slot51ActivityName = Self("slot51ActivityName")
//    static let slot52ActivityName = Self("slot52ActivityName")
//    static let slot53ActivityName = Self("slot53ActivityName")
//    static let slot54ActivityName = Self("slot54ActivityName")
//    static let slot55ActivityName = Self("slot55ActivityName")
//    static let slot56ActivityName = Self("slot56ActivityName")
//    static let slot57ActivityName = Self("slot57ActivityName")
//    static let slot58ActivityName = Self("slot58ActivityName")
//    static let slot59ActivityName = Self("slot59ActivityName")
//    static let slot60ActivityName = Self("slot60ActivityName")
//    static let slot61ActivityName = Self("slot61ActivityName")
//    static let slot62ActivityName = Self("slot62ActivityName")
//    static let slot63ActivityName = Self("slot63ActivityName")
//    static let slot64ActivityName = Self("slot64ActivityName")
//    static let slot65ActivityName = Self("slot65ActivityName")
//    static let slot66ActivityName = Self("slot66ActivityName")
//    static let slot67ActivityName = Self("slot67ActivityName")
//    static let slot68ActivityName = Self("slot68ActivityName")
//    static let slot69ActivityName = Self("slot69ActivityName")
//    static let slot70ActivityName = Self("slot70ActivityName")
//    static let slot71ActivityName = Self("slot71ActivityName")
//    static let slot72ActivityName = Self("slot72ActivityName")
}
